"""Repository rule to detect gfortran library path for cross-platform builds.

On Linux, gfortran's libgfortran.a is typically in the default linker search
path, so just -lgfortran suffices. On macOS with Homebrew GCC, the library
lives under /opt/homebrew/lib/gcc/<version>/ (Apple Silicon) or
/usr/local/lib/gcc/<version>/ (Intel), which is NOT in the default search path.

This rule runs `gfortran --print-file-name=libgfortran.a` to locate the library
and emits a GFORTRAN_LINKOPTS list (possibly including -L<dir>) that can be
loaded into BUILD.bazel.
"""

def _find_gfortran_linkopts(repository_ctx):
    """Return a list of linker flags that resolve libgfortran on any platform."""

    # 1. Ask gfortran where its own library lives.
    result = repository_ctx.execute(
        ["gfortran", "--print-file-name=libgfortran.a"],
        timeout = 10,
    )
    if result.return_code == 0:
        libgfortran_path = result.stdout.strip()
        # If gfortran resolved a full path (not just the bare filename), use it.
        if libgfortran_path and libgfortran_path != "libgfortran.a":
            libdir = libgfortran_path[:libgfortran_path.rfind("/")]
            return ["-L" + libdir, "-lgfortran"]

    # 2. Fall back: probe common Homebrew locations (macOS).
    homebrew_candidates = [
        "/opt/homebrew/lib/gcc/current",   # Apple Silicon, 'current' symlink
        "/opt/homebrew/lib/gcc/14",
        "/opt/homebrew/lib/gcc/13",
        "/opt/homebrew/lib/gcc/12",
        "/usr/local/lib/gcc/current",      # Intel Mac, 'current' symlink
        "/usr/local/lib/gcc/14",
        "/usr/local/lib/gcc/13",
        "/usr/local/lib/gcc/12",
    ]
    for path in homebrew_candidates:
        check = repository_ctx.execute(["test", "-f", path + "/libgfortran.a"])
        if check.return_code == 0:
            return ["-L" + path, "-lgfortran"]

    # 3. Last resort: rely on the system linker's default search path.
    #    This normally works on Linux; on macOS it may fail if gfortran is
    #    from Homebrew and not installed system-wide.
    return ["-lgfortran"]

def _gfortran_detect_impl(repository_ctx):
    linkopts = _find_gfortran_linkopts(repository_ctx)

    # Render as a valid Starlark list literal.
    linkopts_literal = "[" + ", ".join(['"{}"'.format(o) for o in linkopts]) + "]"

    repository_ctx.file("defs.bzl", """# Auto-generated by //tools:gfortran_detect.bzl – do not edit.
GFORTRAN_LINKOPTS = {linkopts}
""".format(linkopts = linkopts_literal))

    repository_ctx.file("BUILD.bazel", "# gfortran configuration package\n")

gfortran_detect = repository_rule(
    implementation = _gfortran_detect_impl,
    # local = True  → re-evaluated whenever the workspace changes.
    # configure = True → re-evaluated when environment variables change.
    local = True,
    configure = True,
)
